fruits = []
fruit1 = input("Enter furit 1:")
fruits.append(fruit1)
fruit2 = input("Enter furit 2:")
fruits.append(fruit2)
fruit3 = input("Enter furit 3:")
fruits.append(fruit3)
fruit4 = input("Enter furit 4:")
fruits.append(fruit4)
fruit5 = input("Enter furit 5:")
fruits.append(fruit5)
fruit6 = input("Enter furit 6:")
fruits.append(fruit6)
fruit7 = input("Enter furit 7:")
fruits.append(fruit7)
print(fruits)
