marks = []
marks1 = int(input("Enter marks 1:"))
marks.append(marks1)
marks2 = int(input("Enter marks 2:"))
marks.append(marks2)
marks3 = int(input("Enter marks 3:"))
marks.append(marks3)
marks4 = int(input("Enter marks 4:"))
marks.append(marks4)
marks5 = int(input("Enter marks 5:"))
marks.append(marks5)
marks6 = int(input("Enter marks 6:"))
marks.append(marks6)

sorted_marks = sorted(marks)
print(sorted_marks)
