s=set()
n1=int(input("Enter the number to add in the set: "))
s.add(n1)
n3=int(input("Enter the number to add in the set: "))
s.add(n3)
n3=int(input("Enter the number to add in the set: "))
s.add(n3)
n8=int(input("Enter the number to add in the set: "))
s.add(n8)
n8=int(input("Enter the number to add in the set: "))
s.add(n8)
n8=int(input("Enter the number to add in the set: "))
s.add(n8)
n8=int(input("Enter the number to add in the set: "))
s.add(n8)
n8=int(input("Enter the number to add in the set: "))
s.add(n8)

print(s)