languages = {}
name = input("Enter your name: ")
language = input("Enter your favorite programming language: ")
languages.update({name:language})
name = input("Enter your name: ")
language = input("Enter your favorite programming language: ")
languages.update({name:language})
name = input("Enter your name: ")
language = input("Enter your favorite programming language: ")
languages.update({name:language})
name = input("Enter your name: ")
language = input("Enter your favorite programming language: ")
languages.update({name:language})
print(languages)